### ISSUE TITLE
complex modifications stuck at fetching data 

### ISSUE THREAD

**Issue by alonsd** [pqrs-org/KE-complex_modifications#659]
https://ke-complex-modifications.pqrs.org/ 

This page seems to not load anything

I need access to the shift modifiers so I can't remove the delay for the shift 

Can you guys please fix it or provide me an alternative download link? 

This is how it looks - 

![image](https://user-images.githubusercontent.com/29747936/77570675-d2fadf00-6ed4-11ea-9c1b-7bf7c7665f1b.png)

And I was looking for the following part - 

![image](https://user-images.githubusercontent.com/29747936/77570902-253c0000-6ed5-11ea-85fa-5c437c32cad2.png)

**Comment by fireflypulse** [comment]
Same problem here. Appears to be an issue with the JSON response, it's empty. 
Because of this Index.vue errors at line 291 in the foreach.

![DevTools_-_ke-complex-modifications_pqrs_org_](https://user-images.githubusercontent.com/5952268/77573229-9657c500-6e8d-11ea-8dd8-19455b24de7e.png)

**Comment by abnmt** [comment]
Should be fixed in my PR #658

**Comment by dudeman** [comment]
Looks like this is still happening or happening again, submitted a pr https://github.com/pqrs-org/KE-complex_modifications/pull/683 to fix some bad json.

**Comment by tekezo** [comment]
Thank you for feedback!
I fixed CI to detect the bad json error.

**Comment by alonsd** [comment]
> Thank you for feedback!
> I fixed CI to detect the bad json error.

Please note that this is a 2 month old issue. It may be useful to fix these thing faster for people to use your product.
