### ISSUE TITLE
errors when trying to make

### ISSUE THREAD

**Issue by sdondley** [pqrs-org/KE-complex_modifications#684]
I made a change to public/groups.json and ran `make` and got the following errors:

```
bash scripts/update-json.sh
check public/json/virtual_machine.json
ok
public/json/virtual_machine.json
ruby scripts/lint-groups.rb
bash scripts/update-public-build.sh
environment: PS1: unbound variable
make: *** [all] Error 1
```

**Comment by tekezo** [comment]
Thank you for feedback!

I fixed this issue at master even I guess this issue is related with your shell configuration.
Please rebase or merge your repository to origin/master.

**Comment by sdondley** [comment]
Thanks. Still getting errors, though. I'm running 'make' from a script, which is probably a non-interactive shell. So the proper environment variables.

**Comment by sdondley** [comment]
[2020-05-09 12:15:48] ERROR - 1 out of 1 task(s) failed:
[2020-05-09 12:15:48] ERROR -   Development:karabiner_contribute_complex_modification failed on <local>
[2020-05-09 12:15:48] ERROR -           Error executing: make.
[2020-05-09 12:15:48] ERROR -           STDOUT:
[2020-05-09 12:15:48] ERROR -           bash scripts/update-json.sh
[2020-05-09 12:15:48] ERROR -           ruby scripts/lint-groups.rb
[2020-05-09 12:15:48] ERROR -           bash scripts/update-public-build.sh
[2020-05-09 12:15:48] ERROR -           STDERR:
[2020-05-09 12:15:48] ERROR -           ../scripts/make-distjson.rb:31:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:31:in `block (3 levels) in <main>'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:11:in `each'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:11:in `block (2 levels) in <main>'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:10:in `each'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:10:in `block in <main>'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:9:in `each'
[2020-05-09 12:15:48] ERROR -                   from ../scripts/make-distjson.rb:9:in `<main>'

**Comment by tekezo** [comment]
Thank you for confirmation!

I believe this change fixed this issue.
https://github.com/pqrs-org/KE-complex_modifications/commit/86d512f94be7cec3f66743e748147eba182dbad9

**Comment by sdondley** [comment]
OK, that fixed it. Thanks! Good work on this software. Very useful.
